# set Java environment
language: java
# set JDK version
jdk: oraclejdk8

# set build environment Ubuntu 14.04 LTS (Trusty Tahr)
dist: trusty
# enable 'sudo' mode (need for Docker service)
sudo: required

services:
  - docker

before_install:
  - docker-compose -f ./docker/docker-compose.yml up -d

before_script:
  - docker-compose -f ./docker/docker-compose.yml down

script:
  - mvn surefire:test -Dtest=IgniteClusterTest
